# Generated by Django 5.2.3 on 2025-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Website domain name', max_length=100)),
                ('tag', models.CharField(choices=[('span', 'span'), ('div', 'div')], help_text='HTML tag (span or div) containing the price', max_length=100, null=True)),
                ('css_selector', models.CharField(choices=[('id', 'id'), ('class', 'class')], help_text='CSS selector type (id or class)', max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Price Selector',
            },
        ),
    ]
