# Generated by Django 5.2.3 on 2025-06-24 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of the page to be scraped')),
                ('status', models.CharField(help_text='Current status of the task (e.g., pending, completed, failed)', max_length=20)),
                ('result', models.TextField(blank=True, help_text='Result of the task execution', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if error occurs during task execution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated')),
                ('user', models.ForeignKey(help_text='User who initiated the task', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Status',
            },
        ),
    ]
